CREATE NONCLUSTERED INDEX IX_Dim_Customer_Name ON project.Dim_Customer
	(
	Name,
	Phone
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX IX_Fact_Product ON project.Fact_Product
	(
	DateKey,
	ProductKey,
	StoreKey
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX IX_Fact_SalesOrder ON project.Fact_SalesOrder
	(
	SourceOnlineKey,
	CustomerKey,
	EmployeeKey,
	DateKey
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO